In [1]:
import pandas as pd

In [2]:
world = pd.read_csv('./Tennis_World_Number_1s.csv')

In [3]:
world

,Tennis_Player,Total_Weeks_at_No_1,Maximum_Consectutive_Weeks_at_no_1,Years_End_no_1,Careers_Wins_Losses,Titles,Prize_Money,Unnamed: 7
0,Roger Federer,310,237,5,1222-265,102,126266005,NaN
1,Pete Sampras,286,102,6,762-222,64,43280489,NaN
2,Ivan Lendl,270,157,4,1068-242,94,21262417,NaN
3,Jimmy Connors,268,160,5,1274-282,109,8641040,NaN
4,Novak Djokovic,264,122,5,871-182,75,134684000,NaN
5,Rafael Nadal,196,56,4,960-196,83,111328858,NaN
6,John McEnroe,170,58,4,881-198,77,12552132,NaN
7,Bjorn Borg,109,46,2,644-135,64,3655751,NaN
8,Andre Agassi,101,52,1,870-274,60,31152975,NaN
9,Lleyton Hewitt,80,75,2,616-262,30,20879934,NaN
10,Stefan Edberg,72,24,2,801-270,41,20630941,NaN
11,Jim Courier,58,27,1,506-237,23,14034132,NaN
12,Gustavo Kuerten,43,30,1,358-195,20,14807000,NaN
13,Andy Murray,41,41,1,663-191,45,61217017,NaN
14,Ilie Nastase,40,40,1,858-320,59,2076761,NaN
15,Mats Wilander,20,20,1,571-222,33,7956101,NaN
16,Andy Roddick,13,13,1,612-213,32,20640030,NaN
17,Boris Becker,12,9,0,713-214,49,25080956,NaN
18,Marat Safin,9,4,0,422-267,15,14373291,NaN
19,Juan Carlos Ferrero,8,8,0,479-262,16,13998165,NaN
20,John Newcombe,8,8,0,552-198,35,1062408,NaN
21,Yevgeny Kafelnikov,6,6,0,609-306,26,23883797,NaN
22,Thomas Muster,6,5,0,625-273,44,12266977,NaN
23,Marcelo Rios,6,4,0,391-192,18,9713771,NaN
24,Carlos Moya,2,2,0,575-319,20,13443970,NaN
25,Patrick Rafter,1,1,0,358-191,11,11133128,NaN